### ISSUE TITLE
Incorrect shape in comment

### ISSUE THREAD

**Issue by murlock1000** [DSaurus/threestudio-mvdream#1]
At #https://github.com/DSaurus/threestudio-mvdream/blob/169668367e46060c2a399906355a0ee4b4765f32/guidance/mvdream_guidance.py#L128C8-L128C8

The comment shows 512x512 but 256x256 shape is used to downscale the images to be provided into the vae.

**Comment by DSaurus** [comment]
Hi @murlock1000 ,

Thank you for your advice! I will fix it.
